steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/kachow:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'kachow:base',
    '-t', 'gcr.io/$PROJECT_ID/kachow:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/kachow:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/kachow:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/kachow:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/kachow:coverage',
    '.'
  ]
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config -f .gitmodules submodule.jwt-cpp.url https://source.developers.google.com/p/studied-slate-346920/r/github_cs130-kachow_jwt-cpp
    git submodule init
    git submodule update
images: ['gcr.io/$PROJECT_ID/kachow:base', 'gcr.io/$PROJECT_ID/kachow:latest', 'gcr.io/$PROJECT_ID/kachow:coverage']
